name: Tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR
  schedule:
    # run at 10am on every Monday
    - cron: '0 10 * * 1'

jobs:
  rust-tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            extra-ldflags: -Wl,--disable-new-dtags
          - os: macos-14
    steps:
      - name: checkout regtests
        uses: actions/checkout@v4

      - name: checkout plumed2
        uses: actions/checkout@v4
        with:
          repository: 'plumed/plumed2'
          path: 'plumed2'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: install dependencies
        env:
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        run: |
          pip install --upgrade pip
          pip install torch==2.6.0 "metatensor-torch >=0.7.5,<0.8.0" featomic[torch]

      - name: configure plumed
        run: |
          TORCH_CMAKE_PREFIX=$(python -c "import torch; print(torch.utils.cmake_prefix_path)")
          TORCH_PREFIX=$(cd "$TORCH_CMAKE_PREFIX/../.." && pwd)

          METATENSOR_CMAKE_PREFIX=$(python -c "import metatensor; print(metatensor.utils.cmake_prefix_path)")
          METATENSOR_PREFIX=$(cd "$METATENSOR_CMAKE_PREFIX/../.." && pwd)

          METATENSOR_TORCH_CMAKE_PREFIX=$(python -c "import metatensor.torch; print(metatensor.torch.utils.cmake_prefix_path)")
          METATENSOR_TORCH_PREFIX=$(cd "$METATENSOR_TORCH_CMAKE_PREFIX/../.." && pwd)

          TORCH_CPPFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"

          TORCH_INCLUDES="-I$TORCH_PREFIX/include -isystem $TORCH_PREFIX/include/torch/csrc/api/include"
          CPPFLAGS="$TORCH_INCLUDES $TORCH_CPPFLAGS -isystem $METATENSOR_PREFIX/include -isystem $METATENSOR_TORCH_PREFIX/include $CPPFLAGS"

          LDFLAGS="-L$TORCH_PREFIX/lib -L$METATENSOR_PREFIX/lib -L$METATENSOR_TORCH_PREFIX/lib $LDFLAGS"

          LDFLAGS="$LDFLAGS -Wl,-rpath,$TORCH_PREFIX/lib"
          LDFLAGS="$LDFLAGS -Wl,-rpath,$METATENSOR_PREFIX/lib -Wl,-rpath,$METATENSOR_TORCH_PREFIX/lib"

          LDFLAGS="$LDFLAGS ${{ matrix.extra-ldflags }}"

          cd plumed2
          ./configure --disable-mpi \
                      --enable-libtorch \
                      --enable-metatensor \
                      --enable-modules=all \
                      LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS"

      - name: show 'config.log'
        if: always()  # show this even if the previous step failed
        run: cat plumed2/config.log

      - name: build plumed
        run: |
          cd plumed2
          make -j2

      - name: run regression tests
        run: |
          source plumed2/sourceme.sh
          make
